# Monitoring
services:
  uptimekuma:
    image: docker.io/louislam/uptime-kuma:1.23.16
    container_name: uptimekuma
    hostname: uptimekuma
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ./config/uptimekuma:/app/data
    healthcheck:
      test: curl -fs http://localhost:3001 || exit 1
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3

  dozzle:
    image: amir20/dozzle:v8.12.16
    container_name: dozzle
    hostname: dozzle
    restart: always
    environment:
      - DOZZLE_REMOTE_HOST=${DOZZLE_REMOTE_HOST}
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s

  # traefik-kop:
  #   image: ghcr.io/jittering/traefik-kop:0.16
  #   container_name: traefik-kop
  #   hostname: traefik-kop
  #   restart: always
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - "REDIS_ADDR=${REDIS_ADDR}"
  #     - "BIND_IP=${SAHAQUIEL_IP}"