# Storage tools
services:
  samba:
    image: dperson/samba:amd64
    container_name: samba
    restart: always
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139/tcp
      - 445:445/tcp
    network_mode: bridge
    mem_limit: 512m
    command: '-u "${SAMBA_USER};${SAMBA_PASS}" -s "Drive;/Drive;yes;no"'
    stdin_open: true
    tty: true
    volumes:
      - /usr/share/zoneinfo/Europe/Madrid:/etc/localtime
      - ${STORAGE}:/Drive

  # Documentation: https://github.com/nextcloud/docker
  # nextcloud:
  #   image: nextcloud:31.0.5
  #   container_name: nextcloud
  #   restart: always
  #   security_opt:
  #     - no-new-privileges:true
  #   depends_on:
  #     - redis
  #     - mariadb
  #   ports:
  #     - 8080:80
  #   environment:
  #     - PUID=${UID}
  #     - PGID=${GID}
  #     - TZ=${TZ}
  #     - MYSQL_HOST=mariadb
  #     - MYSQL_DATABASE=${MYSQL_DATABASE}
  #     - MYSQL_USER=${MYSQL_USER}
  #     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  #     - REDIS_HOST=redis
  #     - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
  #     - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
  #     - NEXTCLOUD_DATA_DIR=/data
  #     - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.home
  #     - OVERWRITECLIURL=http://nextcloud.home
  #     - OVERWRITEHOST=nextcloud.home
  #     - TRUSTED_PROXIES=${TRUSTED_PROXIES}
  #   volumes:
  #     - ./config/before-starting:/docker-entrypoint-hooks.d/before-starting
  #     - ./config/nextcloud:/var/www/html/config
  #     - ${STORAGE}/nextcloud:/data

  redis:
    image: valkey/valkey:8.0.3-bookworm
    container_name: redis
    restart: always
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: redis-cli ping || exit 1
  
  mariadb:
    # Note: Check the recommend version here: https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html#server
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./config/mariadb:/var/lib/mysql