http:
  routers:
    homepage:
      service: homepage
      rule: "Host(`homepage.home`)"
      entrypoints:
        - "web"
  services:
    homepage:
      loadBalancer:
        servers:
        - url: "http://192.168.1.209:3000"
