http:
  routers:
    plex:
      service: plex
      rule: "Host(`plex.home`)"
      entrypoints:
        - "web"
  services:
    plex:
      loadBalancer:
        servers:
        - url: "http://192.168.1.203:32400"
