global:
  checkNewVersion: true
  sendAnonymousUsage: false
api:
  insecure: true
  dashboard: true
log:
  level: DEBUG
  # format: common
entryPoints:
  web:
    address: ":80"
    # (Optional) Redirect to HTTPS
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
  websecure:
    address: ":443"
# certificatesResolvers:
#   myresolver:
#     acme:
#       email: my@email.com
#       storage: /letsencrypt/acme.json
#       dnsChallenge:
#         provider: cloudflare
providers:
  providersThrottleDuration: 2s
  file:
    # watch for dynamic configuration changes
    directory: /etc/traefik
    watch: true