# Reverse Proxy and Tunnels
services:
  traefik:
    image: traefik:v3.4.0
    container_name: traefik
    hostname: traefik
    restart: always
    command:
      - "--configfile=/config.yaml"
    ports:
      - 80:80
      - 8080:8080
      - 443:443
      - 853:853
    environment:
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik/logs:/var/log/traefik/
      - ./config/traefik/acme.json:/acme.json
      - ./config/traefik/config.yaml:/config.yaml:ro
      - ./config/traefik/routers/:/etc/traefik/

  # Documentation: https://github.com/jittering/traefik-kop
  # Use with traefik-kop
  # redis:
  #   image: redis:8.0.0
  #   container_name: redis
  #   hostname: redis
  #   restart: always
  #   ports:
  #     - 6379:6379
  #   environment:
  #     - TZ=${TZ}
  #   command: redis-server --save 60 1 --loglevel warning
  #   volumes: 
  #     - ./config/redis:/data

  # cloudflare:
  #   image: cloudflare/cloudflared:2024.2.0-arm64
  #   container_name: cloudflare
  #   hostname: cloudflare
  #   restart: always
  #   environment:
  #     - TUNNEL_TOKEN=${TUNNEL_TOKEN}
  #   extra_hosts: *rpi-server
  #   command: tunnel --no-autoupdate run
  #   networks:
  #     - rpi-net